<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Evaluations Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            color: #2d3748;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #718096;
        }
        .report-info {
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
        }
        .report-info div {
            margin-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #cbd5e0;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #edf2f7;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f7fafc;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #718096;
        }
        .summary {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #ebf8ff;
            border-radius: 4px;
        }
        .summary h3 {
            margin-top: 0;
            color: #2c5282;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Evaluations Report</h1>
        <p>Generated on {{ date('Y-m-d H:i:s') }}</p>
    </div>

    <div class="report-info">
        <div>
            <strong>Report Type:</strong> Evaluations
        </div>
        <div>
            <strong>Total Records:</strong> {{ $data->count() }}
        </div>
    </div>

    @if($data->count() > 0)
    <div class="summary">
        <h3>Summary</h3>
        <p>
            Total Evaluations: {{ $data->count() }}<br>
            Average Overall Score: {{ number_format($data->avg('overall_score'), 2) }}<br>
            Highest Score: {{ $data->max('overall_score') }}<br>
            Lowest Score: {{ $data->min('overall_score') }}
        </p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Submission ID</th>
                <th>Student Name</th>
                <th>Competition</th>
                <th>Evaluator</th>
                <th>Creativity</th>
                <th>Technical</th>
                <th>Presentation</th>
                <th>Overall</th>
                <th>Comments</th>
                <th>Evaluated At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $evaluation)
            <tr>
                <td>{{ $evaluation->id }}</td>
                <td>{{ $evaluation->submission_id }}</td>
                <td>{{ $evaluation->submission->user->name ?? '' }}</td>
                <td>{{ $evaluation->submission->competition->title ?? '' }}</td>
                <td>{{ $evaluation->evaluator->name ?? '' }}</td>
                <td>{{ $evaluation->creativity_score }}</td>
                <td>{{ $evaluation->technical_score }}</td>
                <td>{{ $evaluation->presentation_score }}</td>
                <td>{{ $evaluation->overall_score }}</td>
                <td>{{ Str::limit($evaluation->comments, 30) }}</td>
                <td>{{ $evaluation->created_at ? $evaluation->created_at->format('Y-m-d H:i:s') : '' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <div class="summary">
        <h3>No Data Found</h3>
        <p>No evaluations found matching the selected criteria.</p>
    </div>
    @endif

    <div class="footer">
        Report generated by {{ config('app.name') }} | Page 1
    </div>
</body>
</html>