<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Submissions Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            color: #2d3748;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #718096;
        }
        .report-info {
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
        }
        .report-info div {
            margin-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #cbd5e0;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #edf2f7;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f7fafc;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #718096;
        }
        .summary {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #ebf8ff;
            border-radius: 4px;
        }
        .summary h3 {
            margin-top: 0;
            color: #2c5282;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Submissions Report</h1>
        <p>Generated on {{ date('Y-m-d H:i:s') }}</p>
    </div>

    <div class="report-info">
        <div>
            <strong>Report Type:</strong> Submissions
        </div>
        <div>
            <strong>Total Records:</strong> {{ $data->count() }}
        </div>
    </div>

    @if($data->count() > 0)
    <div class="summary">
        <h3>Summary</h3>
        <p>
            Total Submissions: {{ $data->count() }}<br>
            Average Score: {{ number_format($data->avg(function($submission) { return $submission->evaluations->avg('overall_score'); }), 2) }}<br>
            Pending Submissions: {{ $data->where('status', 'pending')->count() }}<br>
            Approved Submissions: {{ $data->where('status', 'approved')->count() }}<br>
            Rejected Submissions: {{ $data->where('status', 'rejected')->count() }}
        </p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Student Name</th>
                <th>Competition</th>
                <th>Talent Category</th>
                <th>Title</th>
                <th>Status</th>
                <th>Submitted At</th>
                <th>Avg Score</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $submission)
            <tr>
                <td>{{ $submission->id }}</td>
                <td>{{ $submission->user->name ?? '' }}</td>
                <td>{{ $submission->competition->title ?? '' }}</td>
                <td>{{ $submission->talent->name ?? '' }}</td>
                <td>{{ $submission->title }}</td>
                <td>{{ ucfirst($submission->status) }}</td>
                <td>{{ $submission->submitted_at ? $submission->submitted_at->format('Y-m-d H:i:s') : '' }}</td>
                <td>{{ number_format($submission->evaluations->avg('overall_score') ?? 0, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <div class="summary">
        <h3>No Data Found</h3>
        <p>No submissions found matching the selected criteria.</p>
    </div>
    @endif

    <div class="footer">
        Report generated by {{ config('app.name') }} | Page 1
    </div>
</body>
</html>